name: Build and Deploy Docker Images
on:
  pull_request:
    branches:
      - develop
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_ACCOUNT }}

      - name: Build,tag and push Docker images
        env:
          ECR_ACCOUNT: ${{ secrets.ECR_ACCOUNT }}
          ECR_REPOSITORY: twala
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |

          docker build -t altschool-capstone:latest -f https://github.com/microservices-demo/microservices-demo.github.io/blob/master/Dockerfile
          docker tag altschool-capstone:latest ${{ secrets.ECR_ACCOUNT }}/$ECR_REPOSITORY:latest
          docker push ${{ secrets.ECR_ACCOUNT }}/$ECR_REPOSITORY:latest
         
