# apiVersion: v1
# kind: Service
# metadata:
#   name: capstoneservice
# spec:
#   selector:
#     app: capstone-project
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer


apiVersion: v1
kind: Service
metadata:
  name: capstoneservice
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: capstone-project