---
- name: Deploy Application to EKS
  hosts: localhost
  become: yes
  gather_facts: false
  tasks:
    - name: Authenticate with ECR
      command: "{{ lookup('env', 'AWS_ECR_REGISTRY') | b64decode }}"
      environment:
        AWS_DEFAULT_REGION: "us-east-1"

    - name: Deploy application using Kubernetes manifests
      k8s:
        state: "present"
        definition: "/Users/emomondi/Kubernetes/kubernetes_deployment.yaml"

    - name: Update kubeconfig for EKS cluster
      command: "aws eks update-kubeconfig --region us-east-1 --name capstone"
      environment:
        AWS_DEFAULT_REGION: "eu-central-1"

    - name: Get deployments
      command: "kubectl get deployments"

    - name: Get pods
      command: "kubectl get pods"

    - name: Port-forward to pod
      command: "kubectl port-forward capstone 8080:80"
